// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5cexNGsIyto57Y6KPek8j5q81ubQz94',
    appId: '1:385943815984:web:c94a09f70bebbad1842af5',
    messagingSenderId: '385943815984',
    projectId: 'chatapp-new-7ec36',
    authDomain: 'chatapp-new-7ec36.firebaseapp.com',
    storageBucket: 'chatapp-new-7ec36.firebasestorage.app',
    measurementId: 'G-5XPHTMB0P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAShAEKZZa2UvSv8O-5zVA6nEBeAJyEtQ4',
    appId: '1:385943815984:android:0b9cabf4db014e36842af5',
    messagingSenderId: '385943815984',
    projectId: 'chatapp-new-7ec36',
    storageBucket: 'chatapp-new-7ec36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGH4wdLVf7oHKfSLmdnNxjgsRKxqsssw',
    appId: '1:385943815984:ios:a47d16d3d4c7ccc9842af5',
    messagingSenderId: '385943815984',
    projectId: 'chatapp-new-7ec36',
    storageBucket: 'chatapp-new-7ec36.firebasestorage.app',
    iosBundleId: 'com.example.nexaaura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARGH4wdLVf7oHKfSLmdnNxjgsRKxqsssw',
    appId: '1:385943815984:ios:a47d16d3d4c7ccc9842af5',
    messagingSenderId: '385943815984',
    projectId: 'chatapp-new-7ec36',
    storageBucket: 'chatapp-new-7ec36.firebasestorage.app',
    iosBundleId: 'com.example.nexaaura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY5cexNGsIyto57Y6KPek8j5q81ubQz94',
    appId: '1:385943815984:web:1d28ccba390d8cff842af5',
    messagingSenderId: '385943815984',
    projectId: 'chatapp-new-7ec36',
    authDomain: 'chatapp-new-7ec36.firebaseapp.com',
    storageBucket: 'chatapp-new-7ec36.firebasestorage.app',
    measurementId: 'G-1DHW7YGDH3',
  );
}
